version: '3'

services:
  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - '3000:3000'
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgdev
